---
- name: Update repo cache and install dependencies(dbus) for system hostname configuration
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - dbus

- name: Start dbus.service, if not started
  ansible.builtin.service:
    name: dbus
    state: started

- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ item }}"
  with_items:
    - "{{ inventory_hostname }}"
